# Configure Using Gemfile
# gem 'pg'
#
test:
  adapter: postgresql
  encoding: unicode
  database: challenge_test
  pool: 5
  username: samuel
  password: '123456'

production:
  adapter: postgresql
  encoding: unicode
  database: challenge_production
  pool: 5
  username: samuel
  password: '123456'


development:
  adapter: postgresql
  encoding: unicode
  database: challenge_development
  pool: 5
  username: samuel
  password: 123456
